spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 9000