
INSERT INTO BANCO(ID, NOME) VALUES (100, 'CAIXA');
INSERT INTO BANCO(ID, NOME) VALUES (101, 'SANTANDER');
INSERT INTO BANCO(ID, NOME) VALUES (102, 'BRADESCO');
INSERT INTO BANCO(ID, NOME) VALUES (103, 'ITAU');
INSERT INTO BANCO(ID, NOME) VALUES (104, 'BANCO DO BRASIL');

INSERT INTO CARTAO(ID, NOME, FK_BANCO) VALUES (100, 'CAIXA CREDITO', 100);
INSERT INTO CARTAO(ID, NOME, FK_BANCO) VALUES (101, 'SANTANDER DEBITO', 101);
INSERT INTO CARTAO(ID, NOME, FK_BANCO) VALUES (102, 'BRADESCO POUPANCA', 102);
INSERT INTO CARTAO(ID, NOME, FK_BANCO) VALUES (103, 'ITAU CREDITO', 103);
INSERT INTO CARTAO(ID, NOME, FK_BANCO) VALUES (104, 'BANCO DO BRASIL DEBITO', 104);